const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
    console.log('--- DELETING INITIAL SYNC EXPENSES ---');

    // Find expenses created by automated scripts/API triggers with "Hammadde Ekleme" description
    // These were likely created during initial stock synchronization
    const result = await prisma.expense.deleteMany({
        where: {
            description: { startsWith: 'Hammadde Ekleme:' }
        }
    });

    console.log(`Deleted ${result.count} expense records generated by ingredient sync.`);
}

main()
    .catch(e => console.error(e))
    .finally(() => prisma.$disconnect());
